### ISSUE TITLE
why is install.sh missing?

### ISSUE THREAD

**Issue by peter-linzi** [ahrnbom/sorts#1] opened 2021-09-18 06:16 UTC
Hi！@ahrnbom

Thanks for sharing the work！

- I followed the instructions in `README.md`, it appears that install.sh is missing
```
[ Singularity ] peter@pc:~/sorts$ ./install.sh
bash: ./install.sh: No such file or directory
```

- So I ignore that, and try run `demo.py`, it shows: 
```
[ Singularity ] peter@pc:~/sorts$ python demo.py test_video.mp4 
Failed to load OpenCL runtime
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from det2 import MaskRCNN, pixel_nms
  File "/home/peter/sorts/det2.py", line 11, in <module>
    from detectron2 import model_zoo
  File "/usr/local/lib/python3.6/dist-packages/detectron2/model_zoo/__init__.py", line 8, in <module>
    from .model_zoo import get, get_config_file, get_checkpoint_url, get_config
  File "/usr/local/lib/python3.6/dist-packages/detectron2/model_zoo/model_zoo.py", line 9, in <module>
    from detectron2.modeling import build_model
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/__init__.py", line 2, in <module>
    from detectron2.layers import ShapeSpec
  File "/usr/local/lib/python3.6/dist-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/usr/local/lib/python3.6/dist-packages/detectron2/layers/deform_conv.py", line 11, in <module>
    from detectron2 import _C
ImportError: /usr/local/lib/python3.6/dist-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv
```

- My PC info
system: Ubuntu 18.04.2 LTS
nvidia driver: 440.64
CUDA Version: 10.2

Could you please give some suggests about what probably the problem is and let me figure out？

Thanks!

**Comment by peter-linzi** [comment] 2021-09-18 07:07
@ahrnbom

**Comment by ahrnbom** [comment] 2021-09-20 12:26
Hi!

There are two separate issues here. First one, I made a mistake in the instructions, it's called `setup.sh`, not `install.sh`. Thank you for noticing this! I will fix this shortly.

The second issue is probably due to Detectron2/PyTorch/CUDA version incompatabilities. I will look into this and see if I can change the .def file to fix it. The problem is that the definition files did not specify the version of PyTorch to install. So if you build it now, it'll use a newer PyTorch version, probably incompatible with the Detectron2 version I'm using here.

**Comment by ahrnbom** [comment] 2021-09-20 13:23
You can try replacing `sing.def` with the following, and it should most likely work on your system. 

```Bootstrap: docker
From: nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04

%environment
    export LANG=C.UTF-8
    export LC_ALL=C.UTF-8
    
%post
    apt-get update --fix-missing && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && apt-get install -y python3-dev python3-pip python3-opencv ffmpeg python3-tk git && apt-get clean
    python3 -m pip install -U pip
    python3 -m pip install imageio line_profiler imageio-ffmpeg munkres pytest motmetrics google-colab ninja filterpy==1.4.5 scikit-image==0.17.2 lap==0.4.0 cython
    python3 -m pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
    python3 -m pip install torch==1.8.2+cu102 torchvision==0.9.2+cu102 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
    python3 -m pip install detectron2 -f \
        https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.8/index.html
    
    echo 'alias prof="kernprof -l -v"' >> /etc/bash.bashrc
    echo 'alias python="python3"' >> /etc/bash.bashrc
    
%runscript
    echo "> Inside Singularity now!"
    exec ./start_in_singularity.sh "$@"
```

However, my GPU drivers are too new to be able to test this, since this build doesn't work with CUDA 11.4 which I currently have. I no longer have access to the computer I initially tested this on. 

So for the repository here, I will instead update everything to work with newer CUDA and Nvidia drivers, so that I can at least test it myself.

**Comment by ahrnbom** [comment] 2021-09-20 13:55
For people with modern CUDA, e1f1e3b has now fixed the issue. You can either update your drivers or try the solution I added above.

**Closed as completed by ahrnbom** 2021-09-20 13:55 UTC
